on:
    push:    
      tags:
        - 'v*' 
name: Create Release
  
jobs:
    build:
      name: Upload Release Asset
      runs-on: ubuntu-latest    
      steps:
        - name: Checkout code
          uses: actions/checkout@v3 
  
        - name: Build project 
          run: |
            zip -q -r clean_ubuntu_desktop.zip ./clean_ubuntu_desktop
            zip -q -r clean_ubuntu_wsl.zip ./clean_ubuntu_wsl
            ls -l *.zip

        - name: Generate release tag
          id: tag
          run: |         
              echo "::set-output name=release_tag::$(cat releaseTag.txt)"
              cat releaseTag.txt
    
        - name: Upload Release Asset
          id: upload-release-asset 
          uses: softprops/action-gh-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            name: Release ${{ steps.tag.outputs.release_tag }}   
            tag_name: ${{ steps.tag.outputs.release_tag }}    
            prerelease: false
            draft: false
            body_path: changelog.md
            files: |
             ./*.zip